//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsSA.eRecruitment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApplicantProfile()
        {
            this.ApplicantAttachments = new HashSet<ApplicantAttachment>();
            this.ApplicantContactDetails = new HashSet<ApplicantContactDetail>();
            this.ApplicantExperiences = new HashSet<ApplicantExperience>();
            this.ApplicantLangProficiencies = new HashSet<ApplicantLangProficiency>();
            this.ApplicantReferences = new HashSet<ApplicantReference>();
            this.VerApplicantProfiles = new HashSet<VerApplicantProfile>();
            this.ApplicantQualifications = new HashSet<ApplicantQualification>();
        }
    
        public int ApplicantProfileId { get; set; }
        public int UserId { get; set; }
        public string Surname { get; set; }
        public string FirstNames { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string IdentityNumber { get; set; }
        public int RaceId { get; set; }
        public int GenderId { get; set; }
        public bool Disability { get; set; }
        public string DisabilityDesc { get; set; }
        public bool Citizen { get; set; }
        public string Nationality { get; set; }
        public Nullable<bool> WorkPermit { get; set; }
        public bool PreviousDismissal { get; set; }
        public bool CriminalOffence { get; set; }
        public Nullable<System.DateTime> OccupationRegistrationDate { get; set; }
        public string OccupationRegistrationDesc { get; set; }
        public string MaintUser { get; set; }
        public System.DateTime MaintDate { get; set; }
        public string CriminalOffenceDesc { get; set; }
        public string PreviousDismissedReason { get; set; }
        public Nullable<bool> PendingCriminalCase { get; set; }
        public string PendingCriminalDesc { get; set; }
        public Nullable<bool> PublicServiceDismiss { get; set; }
        public string PublicServiceDismissDesc { get; set; }
        public Nullable<bool> PendingDisciplinary { get; set; }
        public string PendingDisciplinaryDesc { get; set; }
        public Nullable<int> NumberOfExperiencePublic { get; set; }
        public Nullable<int> NumberOfExperiencePrivate { get; set; }
        public Nullable<System.DateTime> OfficialRegistrationDate { get; set; }
        public string OfficialRegistrationNumber { get; set; }
        public Nullable<bool> ResignedPendingDisciplinary { get; set; }
        public string ResignedPendingDisciplinaryDesc { get; set; }
        public Nullable<bool> DischargedOrRetired { get; set; }
        public Nullable<bool> BusinessWithState { get; set; }
        public string BusinessWithStateDesc { get; set; }
        public Nullable<bool> RelinquishBusinessInterest { get; set; }
        public string RaceOtherDesc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicantAttachment> ApplicantAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicantContactDetail> ApplicantContactDetails { get; set; }
        public virtual ApplicantDeclaration ApplicantDeclaration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicantExperience> ApplicantExperiences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicantLangProficiency> ApplicantLangProficiencies { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Race Race { get; set; }
        public virtual ApplicantPubServProhibition ApplicantPubServProhibition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicantReference> ApplicantReferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VerApplicantProfile> VerApplicantProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicantQualification> ApplicantQualifications { get; set; }
        public virtual User User { get; set; }
    }
}
