//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsSA.eRecruitment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantContactDetail
    {
        public int ApplicantContactDetailsId { get; set; }
        public int ApplicantProfileId { get; set; }
        public int LanguageId { get; set; }
        public string CellNumber { get; set; }
        public int ContactMethodId { get; set; }
        public string ContactMethogDetails { get; set; }
        public string MaintUser { get; set; }
        public System.DateTime MaintDate { get; set; }
    
        public virtual ContactMethod ContactMethod { get; set; }
        public virtual Language Language { get; set; }
        public virtual ApplicantProfile ApplicantProfile { get; set; }
    }
}
