//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsSA.eRecruitment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Application()
        {
            this.Requirements = new HashSet<Requirement>();
        }
    
        public int ApplicationId { get; set; }
        public int VacancyId { get; set; }
        public int VerApplicantProfileId { get; set; }
        public int ApplicationStatusId { get; set; }
        public System.DateTime ApplicationStatusDate { get; set; }
        public string MaintUser { get; set; }
        public System.DateTime MaintDate { get; set; }
    
        public virtual ApplicationRequirement ApplicationRequirement { get; set; }
        public virtual ApplicationStatus ApplicationStatus { get; set; }
        public virtual VerApplicantProfile VerApplicantProfile { get; set; }
        public virtual Vacancy Vacancy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requirement> Requirements { get; set; }
    }
}
