//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsSA.eRecruitment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationRequirement
    {
        public int ApplicationId { get; set; }
        public int QualificationScore { get; set; }
        public Nullable<int> KnowledgeScore { get; set; }
        public System.DateTime MaintDate { get; set; }
        public string MaintUser { get; set; }
        public Nullable<int> AgeScore { get; set; }
        public Nullable<int> SouthAfricanCitizenScore { get; set; }
        public Nullable<int> InternshipScore { get; set; }
        public Nullable<int> ProgrammeId { get; set; }
        public string OverallAverage { get; set; }
        public Nullable<int> ManagementScore { get; set; }
        public Nullable<int> TrainingScore { get; set; }
        public Nullable<int> ExperienceScore { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Programme Programme { get; set; }
    }
}
