//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsSA.eRecruitment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRUserRole
    {
        public int HRUserRoleId { get; set; }
        public int HRUserId { get; set; }
        public int HRRoleId { get; set; }
        public System.DateTime MaintDate { get; set; }
        public string MaintUser { get; set; }
    
        public virtual HRRole HRRole { get; set; }
        public virtual HRUser HRUser { get; set; }
    }
}
