//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsSA.eRecruitment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListOfApplication
    {
        public int ApplicationId { get; set; }
        public string ApplicationStatusDesc { get; set; }
        public int VacancyId { get; set; }
        public int VerApplicantProfileId { get; set; }
        public string Surname { get; set; }
        public string FirstNames { get; set; }
        public string JobTitle { get; set; }
        public string MaintUser { get; set; }
        public System.DateTime MaintDate { get; set; }
    }
}
