//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsSA.eRecruitment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListOfApplicationsNew
    {
        public int ApplicationId { get; set; }
        public string ApplicationStatusDesc { get; set; }
        public string ProgrammeDesc { get; set; }
        public string ReferenceNo { get; set; }
        public int AgeScore { get; set; }
        public int InternshipScore { get; set; }
        public int KnowledgeScore { get; set; }
        public int SouthAfricanCitizenScore { get; set; }
        public int QualificationScore { get; set; }
        public string OverallAverage { get; set; }
        public int VacancyId { get; set; }
        public int HasAttachament { get; set; }
        public int ProgrammeId { get; set; }
        public int VerApplicantProfileId { get; set; }
        public string Surname { get; set; }
        public string FirstNames { get; set; }
    }
}
