//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsSA.eRecruitment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewApplicationRequirement
    {
        public int ApplicationId { get; set; }
        public Nullable<int> AnswersGenericQuestionsId { get; set; }
        public Nullable<int> AnswersSpecificQuestionsId { get; set; }
        public int ProgrammeId { get; set; }
    }
}
