//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsSA.eRecruitment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasswordResetRequest
    {
        public int PasswordResetRequestId { get; set; }
        public string ResetCode { get; set; }
        public int UserId { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public int PasswordRequestStatusId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual PasswordRequestStatus PasswordRequestStatus { get; set; }
        public virtual User User { get; set; }
    }
}
