//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsSA.eRecruitment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefreshToken
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string ClientId { get; set; }
        public System.DateTime IssuedUTC { get; set; }
        public System.DateTime ExpiresUTC { get; set; }
        public string ProtectedTicket { get; set; }
        public string TokenId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual User User { get; set; }
    }
}
