//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsSA.eRecruitment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement
    {
        public int Id { get; set; }
        public int ApplicationId { get; set; }
        public Nullable<int> ProgrammeId { get; set; }
        public System.DateTime MaintDate { get; set; }
        public string MaintUser { get; set; }
        public Nullable<int> AnswersGenericQuestionsId { get; set; }
        public Nullable<int> AnswersSpecificQuestionsId { get; set; }
        public string SpecifyAnswer { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
