//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsSA.eRecruitment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacancy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vacancy()
        {
            this.Applications = new HashSet<Application>();
        }
    
        public int VacancyId { get; set; }
        public string JobTitle { get; set; }
        public string OfficeName { get; set; }
        public string DivisionName { get; set; }
        public int NumberOfPosts { get; set; }
        public string KeyPerformanceAreas { get; set; }
        public string Prerequisites { get; set; }
        public string PersonProfile { get; set; }
        public int SalaryId { get; set; }
        public decimal SalaryNotch { get; set; }
        public string RemunerationDescription { get; set; }
        public System.DateTime OpeningDate { get; set; }
        public System.DateTime ClosingDate { get; set; }
        public string ReferenceNumber { get; set; }
        public int StatusId { get; set; }
        public string StatusComment { get; set; }
        public bool IsPermanent { get; set; }
        public string MaintUser { get; set; }
        public System.DateTime MaintDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application> Applications { get; set; }
        public virtual Salary Salary { get; set; }
        public virtual VacancyStatus VacancyStatus { get; set; }
    }
}
