//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsSA.eRecruitment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VerApplicantLangProficiency
    {
        public int VerApplicantLangProficiencyId { get; set; }
        public int VerApplicantProfileId { get; set; }
        public int LanguageId { get; set; }
        public int ReadProficiencyId { get; set; }
        public int SpeakProficiencyId { get; set; }
        public int WriteReadProficiencyId { get; set; }
        public string MaintUser { get; set; }
        public System.DateTime MaintDate { get; set; }
    
        public virtual LanguageProficiency LanguageProficiency { get; set; }
        public virtual LanguageProficiency LanguageProficiency1 { get; set; }
        public virtual LanguageProficiency LanguageProficiency2 { get; set; }
        public virtual Language Language { get; set; }
        public virtual VerApplicantProfile VerApplicantProfile { get; set; }
    }
}
