//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsSA.eRecruitment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VerApplicantAttachment
    {
        public int VerApplicantAttachmentId { get; set; }
        public int VerApplicantProfileId { get; set; }
        public int DocumentTypeId { get; set; }
        public string DocumentFormat { get; set; }
        public byte[] DocumentData { get; set; }
        public string FilePath { get; set; }
        public string LocalFileName { get; set; }
        public string OriginalFileName { get; set; }
        public string MaintUser { get; set; }
        public System.DateTime MaintDate { get; set; }
        public bool IsNew { get; set; }
        public string DocumentDataText { get; set; }
    
        public virtual DocumentType DocumentType { get; set; }
        public virtual VerApplicantProfile VerApplicantProfile { get; set; }
    }
}
