//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsSA.eRecruitment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewApplication
    {
        public string Email { get; set; }
        public string FirstNames { get; set; }
        public string Surname { get; set; }
        public Nullable<int> Age { get; set; }
        public string IdentityNumber { get; set; }
        public string ProgrammeDesc { get; set; }
        public string OverallAverage { get; set; }
        public string QualificationScore { get; set; }
        public string Is_South_African { get; set; }
        public string Done_Internship_Before { get; set; }
    }
}
