//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsSA.eRecruitment.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewApplicantQuestionAnswer
    {
        public string GenericAnswer { get; set; }
        public Nullable<bool> GenericAnswerAutoReject { get; set; }
        public Nullable<int> GenericAnswerWeight { get; set; }
        public string GenericQuestion { get; set; }
        public string SpecificAnswer { get; set; }
        public Nullable<bool> SpecificAnswerAutoReject { get; set; }
        public Nullable<int> SpeficicAnswerWeight { get; set; }
        public string SpecificQuestion { get; set; }
        public int VacancyId { get; set; }
        public int ApplicationId { get; set; }
        public int Id { get; set; }
        public string OtherAnswerDescription { get; set; }
    }
}
